### ISSUE TITLE
How to start telegram-cli for multiple phone numbers on one Ubuntu?

### ISSUE THREAD

**Issue by zqumoplay** [vysheng/tg#1325]
Urgently needed the opportunity. Have tried the methods suggested below, but nothing happens.

**Comment by naveenvhegde** [comment]
telegram-cli stores its config under ~/.telegram-cli. 

**2 WAYS**

1. Create a different user for different phone numbers and distribute telegram-cli binary to each user home directory and configure it.

2. You can export few env variable and run telegram-cli from same user.
example

export TELEGRAM_CONFIG_DIR=~/user1/
export XDG_CONFIG_HOME=~/user1/
export TELEGRAM_HOME=~/user1
~/telegram/telegram-cli -k  ~/telegram/tg-server.pub

export TELEGRAM_CONFIG_DIR=~/user2/
export XDG_CONFIG_HOME=~/user2/
export TELEGRAM_HOME=~/user2
~/telegram/telegram-cli -k  ~/telegram/tg-server.pub

I have this setup and created small bash script to launch each telegram account.

**Comment by Ilhicas** [comment]
The correct way to this is by using the config file at  ~/.telegram-cli

The config file is only commented on initialize and its contents are:

# This is an empty config file
# Feel free to put something here

So how should one edit this file to have multiple profiles ( meaning, multiple phone number and accounts)

You could set the following:

```
default_profile = "profile_1" ; # It defaults to this profile if the flag -p is not set

profile_1 = {
config_directory = ".telegram-cli/profile_1";
msg_num = true;
};

profile_2 = {
config_directory = ".telegram-cli/profile_2";
msg_num = true;
};
```

So that when you run 

`telegram-cli -W -k server.pub - p profile_2 `

You will be using the profile_2 or authenticating it for the first time.

`by running telegram-cli -W -k server.pub `

You will be using the profile_1 or authenticating it for the first time, since you did not pass a -p profile flag, and it defaults to the default user.

This should be better documented, I just spent to much time reading issues.

Don't use multiple directories of telegram as suggested, as after authentication the profiles directories will be created under /.telegram-cli/profile_1 containing auth downloads state files and folders.

**Comment by zqumoplay** [comment]
@naveenvhegde 2-way I have stops working --json

**Comment by zqumoplay** [comment]
@Ilhicas It works if you run multiple accounts at the same time?

**Comment by Ilhicas** [comment]
@zqumoplay it works if you run multiple instances, using different Ports, it runs on 4455 default port.

telegram-cli -W -P 4455 -k <path_to_key> -p profile_1
telegram-cli -W -P 4456 -k <path_to_key> -p profile_2

**Comment by zqumoplay** [comment]
@Ilhicas Oh, and I need for one specific port(

**Comment by Ilhicas** [comment]
NOTE

Forgot to mention previously, the first time you run the profile you should run as root in order to give permission to telegram-cli to create the folders for the profiles specified in the config folder.

use the command argument  telegram-cli -U root <arg> <arg..>

**Comment by naveenvhegde** [comment]
Yeah, port has to be different. 
```
tg       13023     1  0 13:30 ?        00:00:02 ./telegram-cli -R -W -P 4459 -k tg-server.pub --json -v 3
tg       13153     1  0 13:30 ?        00:00:02 ./telegram-cli -R -W -P 4460 -k tg-server.pub --json -v 3
tg       13159     1  0 13:30 ?        00:00:02 ./telegram-cli -R -W -P 4461 -k tg-server.pub --json -v 3
```

**Comment by zqumoplay** [comment]
I do not think that all that can touch the port. Problem solved. Thank you @Ilhicas @naveenvhegde )

**Comment by ramzi111** [comment]
i need to create socket unix for each profile 
how i can do this ?
when i create a socket unix ,socket is runnung on profile and profile 2 isn't running
