### ISSUE TITLE
Limit for send/recc message

### ISSUE THREAD

**Issue by erfan-mehraban** [vysheng/tg#613]
Is there any limitation for send/recv message?
Also for geting history and joining group?

**Comment by jonnywilliamson** [comment]
@erfan-mehraban Yes but telegram have not specified what the sending limits are exactly. They will flood control you if you start spamming etc.

As for the others, I haven't seen a limit - but I'm sure there is.

**Comment by LukeLR** [comment]
This was Discussed multiple Times already, See #407, #534 for example ;) Regarding the gering History Limit, I'd rather guess that there is none, because I've already used the get_history-command to download a 200.000-messages chat history at once, and I didn't get any limit or something. Only messaging limits are known by now, although still there is no information, when they lock in. I never got banned, although, because of a bug, my early implementation of my Lua script caused tg to send several hundred messages in just seconds, and I didn't get a flood error or something.
